/** @import {CampaignState} from './types.js' */

/** @type {CampaignState} */
export const MOCK_CAMPAIGN = {
  campaign: {
    id: 'cmp-portugal-2026-05-04',
    topic: 'Portugal Golden Visa: 5→10 years',
    started_at: '2026-05-04T10:00:00Z',
    source_locale: 'ru',
    rewrite_prompt: 'Update content where Portugal Golden Visa requires 10 years (not 5) for citizenship eligibility. Adjust related context, FAQ, timelines. Sections about possible future law changes should be reframed as already-in-effect facts.',
  },
  progress: {
    total: 6,
    reviewed: 0,
    by_status: { pending: 0, proposed: 6, accepted: 0, edited: 0, skipped: 0, deleted: 0, error: 0 },
  },
  blocks: [
    {
      row_id: 'r-001',
      story_id: '12345',
      story_full_slug: 'ru/blog/residency-permit-portugal',
      story_name: 'ВНЖ в Португалии: программы и условия',
      locale: 'ru',
      block_uid: 'blk-aaa',
      block_path: 'body[3]',
      block_component: 'textBlock',
      affected_fields: ['textMarkdown'],
      original_payload: {
        textMarkdown: 'Стать гражданином Португалии можно через 5 лет. Претендовать на гражданство разрешается тем, кто живёт в Португалии постоянно.',
      },
      llm_match_reason: 'Mentions 5 years as Portugal citizenship eligibility threshold',
      proposed_payload: {
        textMarkdown: 'Стать гражданином Португалии можно через 10 лет. Претендовать на гражданство разрешается тем, кто живёт в Португалии постоянно.',
      },
      edited_payload: null,
      status: 'proposed',
      skip_reason: null,
    },
    {
      row_id: 'r-002',
      story_id: '12345',
      story_full_slug: 'ru/blog/residency-permit-portugal',
      story_name: 'ВНЖ в Португалии: программы и условия',
      locale: 'ru',
      block_uid: 'blk-bbb',
      block_path: 'body[5]',
      block_component: 'faqBlock',
      affected_fields: ['answer'],
      original_payload: {
        answer: 'Гражданство Португалии получают по натурализации через 5 лет жизни в стране.',
      },
      llm_match_reason: 'FAQ answer states 5-year citizenship period',
      proposed_payload: {
        answer: 'Гражданство Португалии получают по натурализации через 10 лет жизни в стране.',
      },
      edited_payload: null,
      status: 'proposed',
      skip_reason: null,
    },
    {
      row_id: 'r-003',
      story_id: '67890',
      story_full_slug: 'blog/portugal-golden-visa-turkey',
      story_name: 'Portugal Golden Visa for Turkish citizens',
      locale: 'en',
      block_uid: 'blk-ccc',
      block_path: 'body[2]',
      block_component: 'textBlock',
      affected_fields: ['textMarkdown'],
      original_payload: {
        textMarkdown: 'After 5 years of legal residence, Golden Visa holders may apply for Portuguese permanent residence. They may also become eligible for citizenship by naturalisation after the same period, provided they meet the legal requirements.',
      },
      llm_match_reason: 'States 5-year period for both PR and citizenship',
      proposed_payload: {
        textMarkdown: 'After 5 years of legal residence, Golden Visa holders may apply for Portuguese permanent residence. They may also become eligible for citizenship by naturalisation after 5 more years, provided they meet the legal requirements.',
      },
      edited_payload: null,
      status: 'proposed',
      skip_reason: null,
    },
    {
      row_id: 'r-004',
      story_id: '67890',
      story_full_slug: 'blog/portugal-golden-visa-turkey',
      story_name: 'Portugal Golden Visa for Turkish citizens',
      locale: 'en',
      block_uid: 'blk-ddd',
      block_path: 'body[7]',
      block_component: 'sectionBlock',
      affected_fields: ['heading', 'textMarkdown'],
      original_payload: {
        heading: 'Possible changes to the Portuguese citizenship rules',
        textMarkdown: 'In 2025, certain Portuguese parties proposed amendments to the Portuguese nationality law which included a longer residence period of 10 years for most applicants. However, the Constitutional Court found some of these provisions unconstitutional.',
      },
      llm_match_reason: 'Section about possible future changes — now reality',
      proposed_payload: {
        heading: 'Updated Portuguese citizenship rules',
        textMarkdown: 'As of 2026, the Portuguese nationality law requires a 10-year residence period for most applicants seeking citizenship by naturalisation. Golden Visa holders fall under this updated rule.',
      },
      edited_payload: null,
      status: 'proposed',
      skip_reason: null,
    },
    {
      row_id: 'r-005',
      story_id: '11122',
      story_full_slug: 'ru/blog/portugal-citizenship-faq',
      story_name: 'Гражданство Португалии — частые вопросы',
      locale: 'ru',
      block_uid: 'blk-eee',
      block_path: 'body[0]',
      block_component: 'leadBlock',
      affected_fields: ['lead'],
      original_payload: {
        lead: 'Получить гражданство Португалии можно через 5 лет легального проживания в стране.',
      },
      llm_match_reason: 'Lead text states 5-year citizenship period',
      proposed_payload: {
        lead: 'Получить гражданство Португалии можно через 10 лет легального проживания в стране.',
      },
      edited_payload: null,
      status: 'proposed',
      skip_reason: null,
    },
    {
      row_id: 'r-006',
      story_id: '11122',
      story_full_slug: 'ru/blog/portugal-citizenship-faq',
      story_name: 'Гражданство Португалии — частые вопросы',
      locale: 'ru',
      block_uid: 'blk-fff',
      block_path: 'body[4]',
      block_component: 'listBlock',
      affected_fields: ['items[0].text', 'items[1].text'],
      original_payload: {
        'items[0].text': 'Прожить в Португалии 5 лет с временным ВНЖ.',
        'items[1].text': 'Сдать экзамен на знание языка после 5 лет проживания.',
      },
      llm_match_reason: 'List items state 5-year requirements',
      proposed_payload: {
        'items[0].text': 'Прожить в Португалии 10 лет с временным ВНЖ.',
        'items[1].text': 'Сдать экзамен на знание языка после 10 лет проживания.',
      },
      edited_payload: null,
      status: 'proposed',
      skip_reason: null,
    },
  ],
};
